### ISSUE TITLE
[BUG]error read ECONNRESET :bug:

### ISSUE THREAD

**Issue by PLQin** [JasonBai007/react-seed#8]
### window X64系统下报bug 
重现bug步骤: 
- npm install -g yarn
- yarn

` 此时出现bug ` 
```
error read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TLSWrap.onread (net.js:568:26)
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this comma
nd.
```

**Comment by JasonBai007** [comment]
You might have guessed it already: it's a connection error.

"ECONNRESET" means the other side of the TCP conversation abruptly closed its end of the connection. This is most probably due to one or more application protocol errors. You could look at the API server logs to see if it complains about something.

参考：https://stackoverflow.com/questions/17245881/node-js-econnreset
